version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./server/default.conf:/etc/nginx/conf.d/default.conf
      - ./files:/usr/share/nginx/html

  bastion-backend:
    image: bastion-backend
    env_file:
      - .env
    container_name: bastion-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./files/:/app/files

